### ISSUE TITLE
Missing FlipEvents.SEND_RESULT constant

### ISSUE THREAD

**Issue by Warvito** [AnswerConsulting/flip-sample-application#18]
Client cannot start training because it is missing to define the FlipEvents.SEND_RESULT at https://github.com/AnswerConsulting/flip-sample-application/blob/942076bbdb0f9c812fd6eb54721c81fc99b35ae3/flip-app/custom/flip.py#L87

resulting into an exception caught at https://github.com/AnswerConsulting/flip-sample-application/blob/942076bbdb0f9c812fd6eb54721c81fc99b35ae3/flip-app/custom/trainer.py#L197

**Comment by robg-answer** [comment]
Hi Walter, I will raise this on the backlog you are correct, this variable is not defined anywhere.
I'm not sure what the purpose of the var is so will need to do some investigation on our side.

Cheers,
Rob.

**Comment by robg-answer** [comment]
Fixed in #23
