### ISSUE TITLE
Follow PEP8 standard when defining imports

### ISSUE THREAD

**Issue by Warvito** [AnswerConsulting/flip-sample-application#19]
According to PEP8 recommendations (https://peps.python.org/pep-0008/#imports):

```
Imports should be grouped in the following order:

    Standard library imports.
    Related third party imports.
    Local application/library specific imports.

You should put a blank line between each group of imports.
```
Several files from the sample-app do not follow this best practice (for example https://github.com/AnswerConsulting/flip-sample-application/blob/942076bbdb0f9c812fd6eb54721c81fc99b35ae3/flip-app/custom/flip.py#L13)

Some of these files have unused imports.
Maybe consider using linters or formatters such as flake8, isort or black (or even pre-commit hooks) to make the python code more consistent

**Comment by yorkeanswer** [comment]
See #21
